### ISSUE TITLE
lib/couch.js:4 leaks ["Couch"]

### ISSUE THREAD

**Issue by sreuter** [tdebarochez/connect-couchdb#12]
Changing ...

``` javascript
Couch = module.exports = function(config) {
```

... to ...

``` javascript
var Couch = module.exports = function(config) {
```

... should do the trick. At least, it doesn't leak anymore and still seems to work as expected...

By the way.. Does anyone use this module at a larger scale? Let's say ~2000 active/concurrent user sessions?

**Comment by tdebarochez** [comment]
Fixed, thanks.

I'm not using it for a lot of active sessions. Benchmarks are welcome :)
