### ISSUE TITLE
cpu and io load

### ISSUE THREAD

**Issue by Jimflip** [tdebarochez/connect-couchdb#13]
Been trying this out on a VPS with a simple app with very low traffic (still in test).

I noticed when using this for session store my cpu usage jumps up 5% (5 minute average) and was then climbing at an approx rate of 2% per week.

Similar with my IO rate, jumped to 50 blocks/sec and then climbed at  a rate of approx 50 blocks average per week (i.e. after running for a week my IO rate had increased by an average of 100 blocks per second).  

I've gone back to using a memorystore and my IO rate and CPU usage has dropped back down to before I used this middleware.

My app is using couchdb elsewhere (seperate DB from session and using cradle).

While I can understand an increase in load due to periodic updating/cleaning, I think there must be a problem somewhere causing the load to increase at such a steady rate.

I tried investigating what could be causing the increase in IO and iotop pointed the finger at kjournald.

Also I'm not actually using the session to store anything yet!

Running on Lindode VPS 512 (just running, a single instance of this node.js app with couchdb).
Ubuntu Server 10.10 with node@0.6.2

├─┬ connect-couchdb@0.2.2 
│ ├─┬ connect@1.8.5 
│ │ ├── formidable@1.0.8 
│ │ ├── mime@1.2.4 
│ │ └── qs@0.4.0 
│ └── request@2.9.3 
├─┬ cradle@0.5.7 
│ ├── vargs@0.1.0 
│ └─┬ vows@0.6.1 
│   └── eyes@0.1.7 
├─┬ express@2.5.3 
│ ├─┬ connect@1.8.5 
│ │ └── formidable@1.0.8 
│ ├── mime@1.2.4 
│ ├── mkdirp@0.0.7 
│ └── qs@0.4.0 
├─┬ handlebars@1.0.2beta 
│ ├─┬ optimist@0.2.8 
│ │ └── wordwrap@0.0.2 
│ └── uglify-js@1.0.7 
├─┬ jade@0.20.0 
│ ├── commander@0.2.1 
│ └── mkdirp@0.2.1 
└─┬ nodemailer@0.2.4 
  └── mimelib-noiconv@0.1.5

If I can help debug/test then just shout.

**Comment by tdebarochez** [comment]
Did you try to increase reapInterval and compactInterval options ? I just want to be sure about problem's origins.

**Comment by Jimflip** [comment]
no I've not touched any options.

I'll set compactInterval to -1 now and see if it that which is causing the issue, I'll let you know tomorrow.

**Comment by Jimflip** [comment]
setting compactInterval to -1 causes:

Assertion failed: (("libev: ev_timer_start called with negative timer repeat value", w->repeat >= 0.)), function ev_timer_start, file src/unix/ev/ev.c, line 2708.
error (status = )

**Comment by tdebarochez** [comment]
You must define compactInterval or reapInterval with a value superior to zero (https://developer.mozilla.org/en/DOM/window.setInterval).

I tried to define a small value (<1000) to this variables and effectively couchdb augment IO rate.

Are you sure that your application does not create multiple connections to couchdb ? Could you provide how you call "new connectCouchDB" ? via mail or pm if you prefer...

**Comment by Jimflip** [comment]
Sure, i understand the params for setInterval, I assumed you was detecting the value -1 in order to disable compaction as it says in documentation ...

// To disable compaction, set compactInterval to -1

I have since set the compactInterval to a value of 900000, the load spikes are visible now and it looks very much like it is due to the compaction.  The sessions database is empty so it will be interesting to see if the load increases over time.

Multiple connections are made to couched, I'm using cradle for my main database.  But there should only be one connection to the sessions database.

'''
var ConnectCouchDB = require('connect-couchdb')(express);

var store =  new ConnectCouchDB(
{
    name: 'app_sessions',
    username: 'admin',
    password: 'secret',
    host: 'localhost',
    compactInterval:900000
});

**Comment by Jimflip** [comment]
Ok got some results, the cpu load seems stable now, but the IO is still linearly increasing, not as much, i suspect 33% as much as i multiplied the compactInterval by 3.

So it looks like there is an issue running compaction with Couchdb periodically (the database is empty), now the question is it to do with couchdb or this middleware.

**Comment by tdebarochez** [comment]
Ok, feel free to re-open issue
