### ISSUE TITLE
Use bulk docs api for session reap

### ISSUE THREAD

**Issue by ianshward** [tdebarochez/connect-couchdb#21]
Session reaping can generate a lot of separate delete requests, which can spike socket usage (since node by default does not use keepalive connections longer than a tick through the event loop) when sessions are reaped.  The [bulk docs api](http://wiki.apache.org/couchdb/HTTP_Bulk_Document_API) could be used to delete all reaped sessions in one request.

**Comment by tdebarochez** [comment]
fixed in #9493181
