### ISSUE TITLE
Simplify the expires view

### ISSUE THREAD

**Issue by qraynaud** [tdebarochez/connect-couchdb#22]
There is no need to have such a complicated view that I'm aware of. Is there a use case you have not yet covered in your code but intend to that would explain the current implementation ? Otherwise I would recommend to get to a simpler view that only does: 

``` javascript
emit(doc.expires, null)
```

You can then request it with

``` javascript
endkey=(+new Date)
```

instead of

``` javascript
endkey='[' + (+new Date()) + ', {}]'
```

You don't need to emit the id as data as you do now because it is already included as a side data in your view (the id is returned with each row in a view if you do not use a reduce on it). You can even go further and use the include_docs=true parameter that will return to you the whole documents you selected in the view. That might look too much but it will prevent you from requesting each objects separately after that (you will to since you have to retrieve the rev field to DELETE them).

I also believe you should add the reduce=false parameter when requesting your expires view just in case someone adds for some strange reason a reduce function to your view. That will prevent it from breaking your code.

If you don't have time to do those optimizations (and agree with the spirit), let me know and I might try to tackle them and provide you with a corresponding pull request.

You can find the doc for most of what I described on the CouchDB wiki here : http://wiki.apache.org/couchdb/HTTP_view_API#Querying_Options

**Comment by tdebarochez** [comment]
I'm ok with a pull request. =)
Don't forget the test case, plz.

Regards,

**Comment by qraynaud** [comment]
Thanks a lot for reviewing this one this quickly. As a last note, I advise you to switch the version number to 0.3/0.4 (depending on your version scheme) for the next release.

I thought about this because I added update instructions. It should let users know they have to be extra careful when upgrading this time.

**Comment by tdebarochez** [comment]
You mean in npm ? you're right, I forget it.
Fixed.
