### ISSUE TITLE
Allow other request options

### ISSUE THREAD

**Issue by emilianox** [tdebarochez/connect-couchdb#25]
Hi, first I want to congratulate you for the work you've done.
I ask you: is it possible to access request params?
Let me explain:
I need to access a remote database that is with Unsigned and request ssl allows me only if I specify "request_defaults": {"strictSSL": false} in the options, but not how to do it in this library.
Thank you !

PS: My apologies for my English, I'm not native English speaker and Google Translate did most of the work.

**Comment by tdebarochez** [comment]
Hi,

This request is for yacw. The request module is not used directly by connect-couchdb module.

Regards,

**Comment by tdebarochez** [comment]
I've update yacw, could you test now, plz ?
