### ISSUE TITLE
YACW Document conflict errors

### ISSUE THREAD

**Issue by ghost** [tdebarochez/connect-couchdb#26]
Hello. Are you still maintaining this module? I am getting a significant number of document conflict errors from your underlying YACW. I'll be looking into this further you but you have nothing there to manage conflicts.

Error: Document update conflict.
... node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:34:15

Seems to occur mostly when logging out or destroying a session.

**Comment by tdebarochez** [comment]
Hello,
Yes, I still maintain this two repositories, but I'm not using them every days.
Do you have any test case for this errors ?

**Comment by paintedbicycle** [comment]
I get this error too, pretty much on every login and logout of my app locally (but not in production)

The error:

```
Error: Document update conflict.
at Request._callback.../connect-couchdb/node_modules/yacw/lib/couch.js:39:15)
```

My set up:

```
    var store = new ConnectCouchDB({
        name: config.db.name,
        reapInterval: 600000,
        compactInterval: 300000,
        setThrottle: 60000
    });

var sess = {
    secret: 'keyboard cat',
    cookie: {},
    store: store,
    saveUninitialized: true,
    resave: true,
}

if ( process.env.NODE_ENV != 'development' ) {

    app.set('trust proxy', 1), // trust first proxy
    sess.cookie.secure = true // serve secure cookies

}

app.use( session(sess) );
```

Log out function:

```
app.get('/logout', function (req, res) {

        req.logout();
        req.flash( 'user-login', { type : "error", title : "Logout successful.", alert : "Come back soon!" } );
        res.redirect( config.path.user );

});
```

Does this happen because of a setting, like reapInterval being too low? Don't quite now how to tweak the defaults.

**Comment by tdebarochez** [comment]
Could you log every request to CouchDB (with call stack) to see where the failure is coming from ?

**Comment by paintedbicycle** [comment]
Sure, I can get you whatever you need. Let me know if you need something other than this.

From node:

```
GET / /
GET /accounts /accounts
POST /accounts/authenticate /accounts/authenticate
GET /projects /projects
GET /accounts?redir=projects/ /accounts
GET /accounts/settings/ /accounts/settings/
GET /accounts?redir=accounts/settings/ /accounts
GET /accounts/settings/ /accounts/settings/
GET /accounts?redir=accounts/settings/ /accounts
GET /accounts/settings/ /accounts/settings/
GET /accounts?redir=accounts/settings/ /accounts
GET /accounts/settings/ /accounts/settings/
GET /accounts?redir=accounts/settings/ /accounts
GET /accounts/settings/ /accounts/settings/
GET /accounts?redir=accounts/settings/ /accounts
GET /accounts/settings/ /accounts/settings/
GET /accounts?redir=accounts/settings/ /accounts
GET /accounts/settings/ /accounts/settings/
GET /accounts?redir=accounts/settings/ /accounts
Error: Document update conflict.
at Request._callback (/Users/username/Sites/myapp/trunk/site/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)
at Request.self.callback (/Users/username/Sites/myapp/trunk/site/node_modules/connect-couchdb/node_modules/yacw/node_modules/request/request.js:121:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/Users/username/Sites/myapp/trunk/site/node_modules/connect-couchdb/node_modules/yacw/node_modules/request/request.js:985:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/Users/username/Sites/myapp/trunk/site/node_modules/connect-couchdb/node_modules/yacw/node_modules/request/request.js:936:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:929:16
at process._tickCallback (node.js:419:13)
```

And from couchdb:

```
 Marker - Jul 7, 2014, 8:32:29 PM
[info] [<0.1359.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1360.0>] 127.0.0.1 - - HEAD /pdb 200
[info] [<0.1374.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1395.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1396.0>] 127.0.0.1 - - HEAD /pdb 200
[info] [<0.1361.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1362.0>] 127.0.0.1 - - PUT /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 201
[info] [<0.1363.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1366.0>] 127.0.0.1 - - HEAD /pdb 200
[info] [<0.183.0>] Starting index update for db: pdb idx: _design/users
[info] [<0.183.0>] Index update finished for db: pdb idx: _design/users
[info] [<0.1364.0>] 127.0.0.1 - - GET /pdb/_design/users/_view/verify?key=[myemailaddress] 200
[info] [<0.1406.0>] 127.0.0.1 - - GET /pdb/5e155e552125a89b99d795ced20002ad 200
[info] [<0.1407.0>] 127.0.0.1 - - PUT /pdb/5e155e552125a89b99d795ced20002ad 201
[info] [<0.1408.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1365.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1367.0>] 127.0.0.1 - - PUT /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 201
[info] [<0.1368.0>] 127.0.0.1 - - HEAD /pdb 200
[info] [<0.1369.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1371.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1370.0>] 127.0.0.1 - - PUT /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 201
[info] [<0.1372.0>] 127.0.0.1 - - GET /pdb/5e155e552125a89b99d795ced20002ad 200
[info] [<0.1373.0>] 127.0.0.1 - - HEAD /pdb 200
[info] [<0.1397.0>] 127.0.0.1 - - GET /pdb/5e155e552125a89b99d795ced20002ad 200
[info] [<0.1400.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1401.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1402.0>] 127.0.0.1 - - PUT /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 201
[info] [<0.1403.0>] 127.0.0.1 - - HEAD /pdb 200
[info] [<0.1416.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1418.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1417.0>] 127.0.0.1 - - PUT /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 201
[info] [<0.1419.0>] 127.0.0.1 - - GET /pdb/5e155e552125a89b99d795ced20002ad 200
[info] [<0.1420.0>] 127.0.0.1 - - HEAD /pdb 200
[info] [<0.1421.0>] 127.0.0.1 - - GET /pdb/5e155e552125a89b99d795ced20002ad 200
[info] [<0.1422.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1423.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1424.0>] 127.0.0.1 - - PUT /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 201
[info] [<0.1425.0>] 127.0.0.1 - - HEAD /pdb 200
[info] [<0.1426.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1428.0>] 127.0.0.1 - - GET /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 200
[info] [<0.1427.0>] 127.0.0.1 - - PUT /pdb/connect-session_u-W_Hv2uAa3Pb9T5SNt_1zfdal_mwLrl 201
[info] [<0.1429.0>] 127.0.0.1 - - GET /pdb/5e155e552125a89b99d795ced20002ad 200
```

...and it just repeats. It's a massive redirect loop which then shuts down the app. If you need the full 'debug' log setting from couch, let me know. Or if you needed something else, please let me know how to get you what you need. Seems weird that it's a redirect, so I double checked by commenting out the couchdb store and just used the memory store. No issues.

Paul

**Comment by tdebarochez** [comment]
Does this loops are a normal behavior of your application ?

EDIT : In couchdb logs, where does the conflict happen ?

**Comment by paintedbicycle** [comment]
No, this is not normal. I cleared both of my logs, then I simply tired to log in to my app and all of this happened!

You can see the document conflict in the node app logs. It crashed and then logs stack.err

**Comment by tdebarochez** [comment]
Yes, I can see the error in your app logs, but not in CouchDB logs, is it normal ? Should not we get 400 error code (or something similar) ?

**Comment by paintedbicycle** [comment]
Ah, sorry, yes only if I do the full 'debug' level errors in Couch, do I see them. They are very long and have some minor private data. Can I email them to you?

**Comment by tdebarochez** [comment]
Of course.

**Comment by tdebarochez** [comment]
Ok, I've got the same error when flooding the refresh button on the `example.js` file. I think the safest way to deal with it is to catch and ignore the conflict.

**Comment by paintedbicycle** [comment]
In your assessment, the errors are all in my code? The redirect issue is somewhere in my app?

**Comment by tdebarochez** [comment]
Yes sure, there isn't any redirection in the connect-couchdb source code. But if you try to save a session before an other process who tried to do the same with an older one, you get a conflict error (see http://couchdb.readthedocs.org/en/latest/intro/overview.html?highlight=conflict#conflicts).

**Comment by paintedbicycle** [comment]
Ok I'll look into this further

**Comment by paintedbicycle** [comment]
Ok, I think there was some issues with this and Passport. At the very least sessions weren't being destroyed properly. Cleaned up now. I think this issue can likely be closed if the OP doesn't disagree...

**Comment by tdebarochez** [comment]
Ok, feel free to re-open if necessary.

**Comment by ghost** [comment]
@paintedbicycle, @tdebarochez Hi guys. So it is possible to recreate @paintedbicycle What had you missed in the cleanup that seemed to clear this up?

**Comment by paintedbicycle** [comment]
I think the biggest change was to explicitly call req.session.destroy() in the logout() function and req.session.save() in the passport authenticate function. Passport and the Passport Local strategy cleaned the cookie but not the session in the store.

**Comment by tdebarochez** [comment]
The problem occur when you have two concurrent commits on the session (ie : two parallel AJAX queries). Cleanup your code or your workflow to avoid this and it should be fine.
Be you should ask you the question : what do I want to do when a conflict arise ? Does I need to keep the first datas committed or the second ?

**Comment by paintedbicycle** [comment]
I'm not aware of any situation in which I'd need an old session. For most applications, I'd imagine destroying all old sessions (for that user) automatically and seamlessly if a new one is set would make sense.
