### ISSUE TITLE
Facing Error in Connect-Couchdb with cloudant 

### ISSUE THREAD

**Issue by jamesrajkumar1992** [tdebarochez/connect-couchdb#34]
Hi,
I have my application hosted in bluemix. I am using connect-couchdb module for session management.
Frequently I am facing the below errors. Please help me on this. I have provided the error logs below. 

App/0Error: null2016-10-26T02:55:58.716+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:55:58.716+0530
App/0 at _stream_readable.js:944:162016-10-26T02:55:53.187+0530
App/0 at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/request/request.js:965:12)2016-10-26T02:55:53.187+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:55:53.187+0530
App/0Error: null2016-10-26T02:55:53.187+0530
App/0 at Request.emit (events.js:95:17)2016-10-26T02:55:53.187+0530
App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)2016-10-26T02:55:33.135+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:55:33.135+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:55:22.750+0530
App/0 at Request.self.callback (/home/vcap/app/node_modules/request/request.js:187:22)2016-10-26T02:55:22.750+0530
App/0 at IncomingMessage.emit (events.js:117:20)2016-10-26T02:55:22.750+0530
App/0 at Request.<anonymous> (/home/vcap/app/node_modules/request/request.js:1044:10)2016-10-26T02:55:22.750+0530
App/0 at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/request/request.js:965:12)2016-10-26T02:55:22.750+0530
App/0 at IncomingMessage.emit (events.js:117:20)2016-10-26T02:54:58.465+0530
App/0 at Request.self.callback (/home/vcap/app/node_modules/request/request.js:187:22)2016-10-26T02:54:58.465+0530
App/0 at Request.self.callback (/home/vcap/app/node_modules/request/request.js:187:22)2016-10-26T02:54:03.012+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:54:03.012+0530
App/0 at Request.<anonymous> (/home/vcap/app/node_modules/request/request.js:1044:10)2016-10-26T02:54:03.012+0530
App/0 at Request.emit (events.js:98:17)2016-10-26T02:54:03.012+0530
App/0Error: null2016-10-26T02:54:03.012+0530
App/0 at _stream_readable.js:944:162016-10-26T02:54:03.012+0530
App/0 at Request.emit (events.js:98:17)2016-10-26T02:53:00.533+0530
App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)2016-10-26T02:53:00.533+0530
App/0 at IncomingMessage.emit (events.js:117:20)2016-10-26T02:53:00.533+0530
App/0 at IncomingMessage.emit (events.js:117:20)2016-10-26T02:52:01.945+0530
App/0 at Request.emit (events.js:98:17)2016-10-26T02:52:01.945+0530
App/0 at _stream_readable.js:944:162016-10-26T02:52:01.945+0530
App/0Error: null2016-10-26T02:52:01.944+0530
App/0 at Request.emit (events.js:98:17)2016-10-26T02:51:59.052+0530
App/0 at Request.emit (events.js:95:17)2016-10-26T02:51:59.052+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:51:59.052+0530
App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)2016-10-26T02:51:59.052+0530
App/0 at IncomingMessage.emit (events.js:117:20)2016-10-26T02:51:59.052+0530
App/0 at _stream_readable.js:944:162016-10-26T02:51:59.052+0530
App/0 at Request.<anonymous> (/home/vcap/app/node_modules/request/request.js:1044:10)2016-10-26T02:51:01.468+0530
App/0 at Request.self.callback (/home/vcap/app/node_modules/request/request.js:187:22)2016-10-26T02:51:01.468+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:51:01.468+0530
App/0 at _stream_readable.js:944:162016-10-26T02:51:01.468+0530
App/0 at IncomingMessage.emit (events.js:117:20)2016-10-26T02:51:01.468+0530
App/0Error: null2016-10-26T02:51:01.468+0530
App/0 at Request.emit (events.js:95:17)2016-10-26T02:51:00.330+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:51:00.330+0530
App/0 at _stream_readable.js:944:162016-10-26T02:51:00.330+0530
App/0 at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/request/request.js:965:12)2016-10-26T02:51:00.330+0530
App/0 at _stream_readable.js:944:162016-10-26T02:50:53.920+0530
App/0 at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/request/request.js:965:12)2016-10-26T02:50:53.920+0530
App/0Error: null2016-10-26T02:50:53.920+0530
App/0 at Request.emit (events.js:98:17)2016-10-26T02:50:53.920+0530
App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)2016-10-26T02:50:53.920+0530
App/0 at _stream_readable.js:944:162016-10-26T02:50:51.496+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:50:51.496+0530
App/0 at Request.<anonymous> (/home/vcap/app/node_modules/request/request.js:1044:10)2016-10-26T02:50:44.603+0530
App/0 at Request.emit (events.js:98:17)2016-10-26T02:50:44.603+0530
App/0 at Request.emit (events.js:95:17)2016-10-26T02:50:44.603+0530
App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)2016-10-26T02:50:44.603+0530
App/0 at Request.emit (events.js:95:17)2016-10-26T02:50:35.964+0530
App/0 at IncomingMessage.emit (events.js:117:20)2016-10-26T02:50:35.964+0530
App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)2016-10-26T02:50:35.964+0530
App/0Error: null2016-10-26T02:50:35.964+0530
App/0 at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/request/request.js:965:12)2016-10-26T02:50:35.964+0530
App/0 at Request.self.callback (/home/vcap/app/node_modules/request/request.js:187:22)2016-10-26T02:50:32.480+0530
App/0 at Request.<anonymous> (/home/vcap/app/node_modules/request/request.js:1044:10)2016-10-26T02:50:32.480+0530
App/0 at process._tickDomainCallback (node.js:492:13)2016-10-26T02:50:32.480+0530
App/0 at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/request/request.js:965:12)2016-10-26T02:50:32.480+0530
App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)2016-10-26T02:50:32.480+0530
App/0 at Request.emit (events.js:95:17)2016-10-26T02:50:31.317+0530
App/0 at Request.<anonymous> (/home/vcap/app/node_modules/request/request.js:1044:10)2016-10-26T02:50:31.317+0530
App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)2016-10-26T02:50:31.317+0530
App/0 at Request.emit (events.js:95:17)2016-10-26T02:50:29.317+0530
App/0 at Request.self.callback (/home/vcap/app/node_modules/request/request.js:187:22)2016-10-26T02:50:29.317+0530
App/0Error: null2016-10-26T02:50:29.316+0530
App/0 at IncomingMessage.emit (events.js:117:20)

**Comment by tdebarochez** [comment]
Hi,

Could you provide some step to reproduce ?
Without it, I can't find the problem...

Regards,

**Comment by jamesrajkumar1992** [comment]
Hi,
Whenever there is a hit to our API or our website page, new session is being created in cloudant. Frequently there is a error in logs which occurs in App/0 at Request._callback (/home/vcap/app/node_modules/connect-couchdb/node_modules/yacw/lib/couch.js:39:15)

Sorry I am not sure how to reproduce this error.

Have you ever faced this kind of error ?

**Comment by tdebarochez** [comment]
Nop, never.
I can only tell you there have been an error with no "reason" (cf: https://github.com/tdebarochez/yacw/blob/master/lib/couch.js#L39).
Try to add some debug information in this file to understand what's append exactly.
